server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml  

clients:
  - url: http://64.227.132.20:3100/loki/api/v1/push  # Loki endpoint

scrape_configs:
  - job_name: flask-api
    static_configs:
      - targets: [localhost]
        labels:
          job: flask-api
          app: demo-api
          env: production
          __path__: /var/log/flask-app.log

    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            message: message
            request_id: request_id
            endpoint: endpoint
            duration_ms: duration
            http_status: http_status
            error_type: error_type
            severity: severity

      - labels:
          level: ""
          endpoint: ""
          severity: ""
          error_type: ""
          http_status: ""
          duration_ms: ""

      - timestamp:
          source: time
          format: RFC3339