[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "locust>=2.33.2",
    "prometheus-client>=0.21.1",
    "requests>=2.32.3",
]
