{
 "title": "Golden Signal Monitoring Dashboard",
 "description": "added initial latency, saturation and error dashboards",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "endpoint", "query": "/api/data, /api/health" }
  ]
 },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(api_request_duration_seconds_bucket{endpoint=\"${endpoint}\", http_status=\"200\"}[5m])) by (le)\r\n)",
     "legendFormat": "OK"
    },
    {
     "expr": "histogram_quantile(0.95, \r\n  sum(rate(api_request_duration_seconds_bucket{endpoint=\"${endpoint}\", http_status=~\"[45]..\"}[5m])) by (le)\r\n)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(api_request_total{endpoint=\"${endpoint}\"}[5m]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Error Rates (by Severity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(api_error_count_total{endpoint=\"${endpoint}\", severity=\"mild\"}[5m])) / sum(rate(api_error_count_total{endpoint=\"${endpoint}\"}[5m])) * 100",
     "legendFormat": "Mild"
    },
    {
     "expr": "sum(rate(api_error_count_total{endpoint=\"${endpoint}\", severity=\"critical\"}[5m])) / sum(rate(api_error_count_total{endpoint=\"${endpoint}\"}[5m])) * 100",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(rate(api_error_count_total{endpoint=\"${endpoint}\", severity=\"external\"}[5m])) / sum(rate(api_error_count_total{endpoint=\"${endpoint}\"}[5m])) * 100",
     "legendFormat": "External"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(api_error_count_total{endpoint=\"${endpoint}\", http_status=~\"4..\"}[5m])) / sum(rate(api_request_total{endpoint=\"${endpoint}\"}[5m])) * 100",
     "legendFormat": "4xx Errors"
    },
    {
     "expr": "sum(rate(api_error_count_total{endpoint=\"${endpoint}\", http_status=~\"5..\"}[5m])) / sum(rate(api_request_total{endpoint=\"${endpoint}\"}[5m])) * 100",
     "legendFormat": "5xx Errors"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"209.38.123.115:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Saturation (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "System Saturation (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "API Exception Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"flask-api\"} \r\n| json \r\n| http_status !~ \"200|^$\"\r\n| endpoint=\"${endpoint}\" \r\n| line_format \"{{.time}} [{{.level}}] {{.endpoint}} ({{.duration}}ms) | [MESSAGE] {{.message}} | severity = {{.severity}}\""
    }
   ]
  }
 ]
}